version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secretpassword
    container_name: postgres
    volumes:
      - C:/Users/Bibek/Desktop/Web Dev/docker-databases/postgresql/data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secretpassword
    ports: 
      - '8080:80'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-U",
          "postgres",
          "-d",
          "postgres"
        ]
      interval: "1s"
      timeout: "10s"
      retries: 10
      start_period: "1s"

    depends_on:
      - db
    
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest_cms_app
    environment:
      - PORT=${PORT} 
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src 
volumes: 
  app:
    